name: On Outside Trigger

on: 
  repository_dispatcher:
    types: [trigger-test]

jobs:
  run:
    name: Run stuff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"